---
- hosts: tomcatserver
  gather_facts: no

  tasks:
    - name: Copy WAR file to tomcatserver
      copy:
        src: "~/.jenkins/workspace/Assessement1/target/addressbook-2.0.war"
        dest: "/opt/tomcat/apache-tomcat-9.0.75/webapps/"
